Existing CICD updates

diff --git a/.github/workflows/unit_testing.yaml b/.github/workflows/unit_testing.yaml
--- a/.github/workflows/unit_testing.yaml
+++ b/.github/workflows/unit_testing.yaml
@@ -3,28 +3,40 @@ name: Unit Testing
 on:
   push:
     branches: [main, staging, dev]
+    paths: ['**.py', '**.pyc', '**.pyo', '**.pyd']
   pull_request:
     branches: [main, staging, dev]
+    paths: ['**.py', '**.pyc', '**.pyo', '**.pyd']
+
 
 jobs:
   main:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v4
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
       - name: Set up Python "3.11"
         uses: actions/setup-python@v4
         with:
           python-version: "3.11"
-      - name: Setup .netrc
-        run: |
-          echo -e "machine github.com\nlogin ${{ secrets.CUSTOM_GITHUB_TOKEN }}\npassword \n" > ~/.netrc
-          chmod 600 ~/.netrc
-      - name: Install dependencies
-        run: |
-          pip install .
-          pip install pytest
+
+      - name: Setup Just
+        uses: ./.github/actions/setup-just
+
       - name: Test with pytest
+        id: pytest
+        continue-on-error: true
         run: |
-          set +e
-          make unit-test
-          exit $(( $? == 5 ? 0 : $? ))
+          just unit-test
+
+      - name: Check pytest result
+        if: steps.pytest.outcome == 'failure'
+        run: |
+          if [ ${{ steps.pytest.exitcode }} -eq 5 ]; then
+            echo "Pytest exited with code 5 (no tests collected), treating as success"
+            exit 0
+          else
+            echo "Pytest failed with exit code ${{ steps.pytest.exitcode }}"
+            exit ${{ steps.pytest.exitcode }}
+          fi
